### ISSUE TITLE
LDproxy: some SNPs have inverted REF/ALT

### ISSUE THREAD

**Issue by PlatonB** [CBIIT/nci-webtools-dceg-linkage#139]
Let's try to find in-LD SNPs, for example, for rs10141135. Let the population be EUR, and the window be 100000.

Part of the alleles matches dbSNP, but part is inverted. The results shown in the table below are trimmed by r2 >= 0.95.

| ID | LDproxy | dbSNP |
| --- | ----------- | ---------- |
| rs10145102 | G/A | A/G |
| rs12896776 | G/T | T/G |
| rs12888447 | T/C | C/T |
| rs12888938 | G/A | A/G |
| rs12894831 | G/A | A/G |
| rs11623778 | G/A | A/G |
| rs12882512 | A/G | G/A |
| rs7152815 | T/C | C/T |
| rs12894947 | G/A | A/G |
| rs61994836 | C/T | T/C |
| rs11626026 | G/A | A/G |

I was able to reproduce the bug for other SNPs as well.

**Comment by kvnjng** [comment]
All variant allele information is pulled from the 1000 Genomes Project data and thus will reflect the allele representations there.

**Comment by PlatonB** [comment]
@kvnjng In these cases, there are mismatches with both dbSNP and 1000G.

**Comment by PlatonB** [comment]
@kvnjng I guessed. The reason is that LDLink uses GRCh37 data. I compared the LDLink output to the GRCh38 source.
