### ISSUE TITLE
SNPclip kept variants not ordered by input order

### ISSUE THREAD

**Issue by bramburger** [CBIIT/nci-webtools-dceg-linkage#182]
Dear LDlink developers,

Thank you for making these tools available!
I have a small question about the SNPclip tool in the LD tools family, that I hope you can help me with.

The documentation for SNPclip says that for the output LD thinned variant list

> Variants are ordered by input order, so to force a variant to be in the LD thinned list it should be at the top of the input list. 

This leads me to believe that for a given list, the variant at the top of the list will always be included in the thinned list. That is, given the list

```
chr1:48367606
chr1:48367400
chr1:48357036
chr1:48364993
chr1:48361096
chr1:48365462
chr1:48358162
chr1:48361878
chr1:48362713
chr1:48369928
chr1:48367147
chr1:48360746
chr1:48370525
chr1:48361762
chr1:48360525
```

`chr1:48367606` should be in the thinned list. However, the output I get is (with European reference, R2 at 0.2, and MAF at 0.001)

```
RS Number	Position	Alleles	Details
rs72898135	chr1:48367606	T=0.997, G=0.003	Variant in LD with rs72898121 (R2=0.7493), variant removed.
rs2201691	chr1:48367400	C=0.984, T=0.016	Variant in LD with rs76820922 (R2=1.0), variant removed.
rs6666907	chr1:48357036	C=0.47, G=0.53	Variant kept.
rs11583163	chr1:48364993	G=0.984, C=0.016	Variant in LD with rs76820922 (R2=1.0), variant removed.
rs1497097	chr1:48361096	G=0.897, T=0.103	Variant in LD with rs11211625 (R2=1.0), variant removed.
rs7532992	chr1:48365462	C=0.367, T=0.633	Variant in LD with rs6666907 (R2=0.3323), variant removed.
rs72898121	chr1:48358162	A=0.996, C=0.004	Variant kept.
rs10890512	chr1:48361878	C=0.372, T=0.628	Variant in LD with rs6666907 (R2=0.318), variant removed.
rs2088361	chr1:48362713	T=0.634, C=0.366	Variant in LD with rs6666907 (R2=0.3352), variant removed.
rs575626200	chr1:48369928	C=0.998, T=0.002	Variant kept.
rs12724210	chr1:48367147	T=0.389, C=0.611	Variant in LD with rs6666907 (R2=0.3454), variant removed.
rs184550965	chr1:48360746	G=0.994, A=0.006	Variant kept.
rs1556981	chr1:48370525	T=0.126, C=0.874	Variant in LD with rs11211625 (R2=0.798), variant removed.
rs76820922	chr1:48361762	C=0.984, T=0.016	Variant kept.
rs11211625	chr1:48360525	C=0.897, T=0.103	Variant kept.
```

Where the order of which variants are kept rather looks to be based on the position on the chromosome.
I was wondering whether I am misunderstanding the documentation, or whether this is unintended behaviour?

Thank you, and kind regards,
Bram

**Comment by xiaoyao00** [comment]
Hi Bram,

Thanks for reporting this. Sorry about the confusing. We have fixed this issue. The new release uses user input order to do the thinning. Please check https://ldlink.nci.nih.gov/?tab=home for the update. Let me know if you have any other questions. 

Best,
Judy

**Comment by bramburger** [comment]
Hi Judy,

Thank you for the quick response and fix!

Kind regards,
Bram
